package Medico;

public enum Especialidade {
    CARDIOLOGIA,
    ANESTESIOLOGIA,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    PNEUMOLOGIA,
    OBSTERICIA,
    PSIQUIATRIA,
    CIRUGIA_GERAL,
    MEDICINA_TRABALHO,
    MEDICINA_DESPORTIVA,
    MEDICINA_FISICA_E_REABILITCAO,
    MEDICINA_GERAL_E_FAMILIAR

}
